server:
  port: 8080

spring:
  application:
    name: inkstone-task
  datasource:
    url: jdbc:postgresql://localhost:5432/inkstone_task
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.inkstonetask.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.inkstonetask: info
