CREATE DOMAIN JSONB AS JSON;

CREATE TABLE task (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_name VARCHAR(200) NOT NULL,
  task_type VARCHAR(50),
  content TEXT,
  status VARCHAR(32) NOT NULL,
  priority INT NOT NULL DEFAULT 0,
  plan_start_time TIMESTAMP,
  plan_end_time TIMESTAMP,
  actual_start_time TIMESTAMP,
  actual_end_time TIMESTAMP,
  max_retry_count INT NOT NULL DEFAULT 3,
  retry_count INT NOT NULL DEFAULT 0,
  executor_type VARCHAR(32),
  executor_config JSONB,
  calendar_flag SMALLINT NOT NULL DEFAULT 0,
  deleted SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_task_status_start_time ON task(status, plan_start_time);
CREATE INDEX idx_task_calendar_time ON task(calendar_flag, plan_start_time, plan_end_time);

CREATE TABLE task_dispatch_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL,
  queue_status VARCHAR(32) NOT NULL,
  priority INT NOT NULL DEFAULT 0,
  next_trigger_time TIMESTAMP NOT NULL,
  worker_id VARCHAR(64),
  retry_count INT NOT NULL DEFAULT 0,
  fail_reason VARCHAR(1000),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_queue_task_id ON task_dispatch_queue(task_id);
CREATE INDEX idx_queue_status_trigger ON task_dispatch_queue(queue_status, next_trigger_time);

CREATE TABLE task_execute_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL,
  queue_id BIGINT,
  execute_status VARCHAR(32) NOT NULL,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  result_msg VARCHAR(2000),
  error_stack TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_execute_log_task_id ON task_execute_log(task_id);
CREATE INDEX idx_execute_log_queue_id ON task_execute_log(queue_id);

CREATE TABLE task_operation_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL,
  operation_type VARCHAR(32) NOT NULL,
  operator_name VARCHAR(100),
  operation_desc VARCHAR(1000),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_operation_log_task_id ON task_operation_log(task_id);
